# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
$(FLOAT_OBJ): 
	rm -rf obj/$(LIB_COMMON_DIR)/
	mkdir -p obj/$(LIB_COMMON_DIR)/
	gcc -c -m32 -fno-builtin -o obj/$(LIB_COMMON_DIR)/FLOAT.o  -I $(LIB_COMMON_DIR)	$(LIB_COMMON_DIR)/FLOAT.c 

